# Generated by Django 5.2.11 on 2026-02-13 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_google_id_user_is_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_verified",
        ),
    ]
